### ISSUE TITLE
json file format for snli?

### ISSUE THREAD

**Issue by matthias-samwald** [adamzjk/SNLI-Keras#1]
Seems like great work!
Unfortunately, the current codebase does not work with the official SNLI JSONL. I tried converting JSONL to JSON, but it still does not work. I assume you created some kind of derivative versions of the original files that the scripts need?
Could you please share these files?

**Comment by hadifar** [comment]
Same problem! Would you please share your modified files?

**Comment by matthias-samwald** [comment]
That won't help, because it is still the wrong format. :/

**Comment by naayaaa** [comment]
the function `create_standard_attention_model` and  `create_enhanced_attention_model` is the core part of this project, you can preprocess SNLI in your own.

it quite simple, you only need two files:

- GloVe word embeddings glove.840B.300d.txt as you can easily download it from their website.

- simplified SNLI dataset, download the original dataset from their website, and transform it as below:

file train.json validation.json test.json contains data in format [[all premise sentences], [all hypothesis sentences], [all labels]]

**Comment by bilalghanem** [comment]
@adamzjk the format that you mention is not clear:

> [all premise sentences]
is it a list inside the json?

Could you provide the original files?
