### ISSUE TITLE
Can't run results 88%

### ISSUE THREAD

**Issue by Accool** [adamzjk/SNLI-Keras#2]
hi , I read your code carefully, trained on my machine and could not reach the results of the thesis. The result I got with ESIM was 83%，Can you tell me your own results, thank you

**Comment by chledowski** [comment]
Hi,
did you find a way to get to 88%? I think that this implementation might be missing a few things:
1) trainable embeddings
2) CuDNNLSTM instead of LSTM makes the training 10x faster.

Im working to get 88% acc with Keras, but am not still there (87%)

**Comment by naayaaa** [comment]
https://github.com/adamzjk/SNLI-Keras/issues/3
